bitbake: Revert "fetch2/local: Fix?"
This reverts commit 373b92d12788c2d2f6f50f17f80ded7f94b2c556.

test_fetch_file_mirror_of_mirror (bb.tests.fetch.FetcherNetworkTest.test_fetch_file_mirror_of_mirror)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/build/poky/bitbake/lib/bb/tests/fetch.py", line 959, in test_fetch_file_mirror_of_mirror
    self.assertEqual(os.path.getsize(self.dldir + "/bitbake-1.0.tar.gz"), 57749)
AssertionError: 7061 != 57749

test_urireplace (bb.tests.fetch.MirrorUriTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pokybuild/yocto-worker/oe-selftest-armhost/build/bitbake/lib/bb/tests/fetch.py", line 500, in test_urireplace
    self.assertEqual([v], newuris)
AssertionError: Lists differ: ['file:///somewhere/1234/sstate-cache/sstate-xyz.tgz'] != ['file:///somewhere/1234/sstate-cache']
First differing element 0:
'file:///somewhere/1234/sstate-cache/sstate-xyz.tgz'
'file:///somewhere/1234/sstate-cache'
- ['file:///somewhere/1234/sstate-cache/sstate-xyz.tgz']
?                                      ---------------
+ ['file:///somewhere/1234/sstate-cache']

Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>